### ISSUE TITLE
可以使用最新版的etcd3.4.7吗？

### ISSUE THREAD

**Issue by tomener** [smallnest/libkv-etcdv3-store#2]

**Comment by smallnest** [comment]
本项目依赖libkv等项目，它依赖的是
![image](https://user-images.githubusercontent.com/865763/78864620-8b488b80-7a6e-11ea-9afe-fd9464f7eedb.png)

所以me没办法更新。

目前etcd和go module问题较多，当前的go.mod是一个非常不容易的可运行的版本。

如果将来etcd和相关的依赖它的库可以痛快的使用etcd最高的版本的话，我会更新go.mod

**Comment by smallnest** [comment]
etcd的一些对go module不友好的设计：

![image](https://user-images.githubusercontent.com/865763/78865688-a1574b80-7a70-11ea-8422-8764084e9ed3.png)
