### ISSUE TITLE
libkv-etcdv3-store/etcdv3.go 文件问题

### ISSUE THREAD

**Issue by mosesed** [smallnest/libkv-etcdv3-store#3]
"github.com/coreos/etcd/clientv3/concurrency" 
已经弃用, 请改成.
"github.com/etcd-io/etcd/clientv3/concurrency"

**Comment by smallnest** [comment]
etcd并不能友好的支持go module, see https://colobu.com/2020/04/09/accidents-of-etcd-and-go-module/
所以等go module支持完美才能升级etcd、bbolt等。

目前go.mod是一个可工作的各种依赖
